name: MdBook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get mdbook versions
      id: get-ver
      run: |
        echo "::set-output name=ver::$(cargo search --limit 1 mdbook | awk -F\" '{print $2}')-$(cargo search --limit 1 mdbook-katex | awk -F\" '{print $2}')"
      shell: bash
    - name: Cache mdbook and katex # cache key contains latest mdbook and mdbook-katex versions. Needs recompilation if changed
      id: cache-mdbook
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/mdbook
          ~/.cargo/bin/mdbook-katex
        key: ${{ runner.os }}-mdbook-${{ steps.get-ver.outputs.ver }}
    - name: Install mdbook # Run install only if cache missed
      if: steps.cache-mdbook.outputs.cache-hit != 'true'
      working-directory: ./algo-book
      run: sh install-mdbook.sh
    - name: Build book
      working-directory: ./algo-book
      run: mdbook build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./algo-book/book
